# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 12:41
from __future__ import unicode_literals

from django.db import migrations
import edc_base.model.fields.uuid_auto_field


class Migration(migrations.Migration):

    dependencies = [
        ('call_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcall',
            name='history_id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcall',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, db_index=True, editable=False, help_text='System auto field. UUID primary key.'),
        ),
        migrations.AlterField(
            model_name='historicallog',
            name='history_id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicallog',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, db_index=True, editable=False, help_text='System auto field. UUID primary key.'),
        ),
        migrations.AlterField(
            model_name='historicallogentry',
            name='history_id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicallogentry',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, db_index=True, editable=False, help_text='System auto field. UUID primary key.'),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
    ]
