# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('call_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcall',
            name='id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.'),
        ),
        migrations.AlterField(
            model_name='historicallog',
            name='id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.'),
        ),
        migrations.AlterField(
            model_name='historicallogentry',
            name='id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.'),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
    ]
