# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_manager', '0002_auto_20160607_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallogentry',
            name='appt_reason_unwilling_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Other reason, please specify ...'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='appt_reason_unwilling_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Other reason, please specify ...'),
        ),
    ]
