# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('call_manager', '0002_auto_20160625_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcall',
            name='history_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicallog',
            name='history_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicallogentry',
            name='history_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
