# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django_crypto_fields.fields.encrypted_text_field


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdiscussion',
            name='comment',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=250, null=True, verbose_name='Additional comment that may assist in analysis of this discussion'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectgroup',
            name='category',
            field=models.CharField(choices=[('not_linked', 'Not linked-to-care'), ('linked_only', 'Linked-to-care only'), ('initiated', 'Initiated ART')], max_length=25),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='category',
            field=models.CharField(choices=[('not_linked', 'Not linked-to-care'), ('linked_only', 'Linked-to-care only'), ('initiated', 'Initiated ART')], max_length=25),
        ),
    ]
