# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='first_arv',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='pims_art_initiation_date',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='pims_registration_date',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='referral_appt_dt',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='t1_visit_date',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
