# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdiscussionrecording',
            name='played',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='interviewrecording',
            name='played',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalpotentialsubject',
            name='category',
            field=models.CharField(choices=[('not_linked', 'Not linked-to-care'), ('linked_only', 'Linked-to-care only'), ('DEFAULTER', 'Defaulter'), ('initiated', 'Initiated ART'), ('t1_initiated', 'Initiated ART at T1')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalsubjectgroup',
            name='category',
            field=models.CharField(choices=[('not_linked', 'Not linked-to-care'), ('linked_only', 'Linked-to-care only'), ('DEFAULTER', 'Defaulter'), ('initiated', 'Initiated ART'), ('t1_initiated', 'Initiated ART at T1')], max_length=25),
        ),
        migrations.AlterField(
            model_name='potentialsubject',
            name='category',
            field=models.CharField(choices=[('not_linked', 'Not linked-to-care'), ('linked_only', 'Linked-to-care only'), ('DEFAULTER', 'Defaulter'), ('initiated', 'Initiated ART'), ('t1_initiated', 'Initiated ART at T1')], max_length=25),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='category',
            field=models.CharField(choices=[('not_linked', 'Not linked-to-care'), ('linked_only', 'Linked-to-care only'), ('DEFAULTER', 'Defaulter'), ('initiated', 'Initiated ART'), ('t1_initiated', 'Initiated ART at T1')], max_length=25),
        ),
    ]
