# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectconsent',
            name='registered_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edc_registration.RegisteredSubject'),
        ),
    ]
