# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0002_auto_20160602_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='age_at_interview',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='cd4_value',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='viral_load',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
