# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0003_auto_20160805_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectlocator',
            name='subject_identifier',
            field=models.CharField(db_index=True, editable=False, max_length=50, null=True, verbose_name='Subject Identifier'),
        ),
        migrations.AddField(
            model_name='subjectlocator',
            name='subject_identifier',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='Subject Identifier'),
        ),
    ]
