# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0003_historicalgroupdiscussion_historicalgroupdiscussionlabel_historicalinterview_historicalsubjectlocato'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpotentialsubject',
            name='contacted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='potentialsubject',
            name='contacted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
