# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_crypto_fields.fields.firstname_field


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0004_auto_20160809_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpotentialsubject',
            name='source',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='potentialsubject',
            name='source',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='category',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='clinic_receiving_from_t1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='currently_pregnant',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='ever_taken_arv_t1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='first_arv_t1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='first_name',
            field=django_crypto_fields.fields.firstname_field.FirstnameField(help_text=' (Encryption: RSA local)', max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='keepme',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='keepme_ahs',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='keepme_bhs',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='on_arv_t1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='pims_art_date',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='pims_reg_date',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='plot_identifier',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='post_t0_link',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='post_t1_initiate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='source',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='sub_category',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='visit_date_t0',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='visit_date_t1',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpotentialsubject',
            name='first_name',
            field=django_crypto_fields.fields.firstname_field.FirstnameField(help_text=' (Encryption: RSA local)', max_length=71, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='potentialsubject',
            name='first_name',
            field=django_crypto_fields.fields.firstname_field.FirstnameField(help_text=' (Encryption: RSA local)', max_length=71, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='pair',
            field=models.IntegerField(null=True),
        ),
    ]
