# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 18:53
from __future__ import unicode_literals

from django.db import migrations
import django_crypto_fields.fields.lastname_field


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0004_rawdata_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='last_name',
            field=django_crypto_fields.fields.lastname_field.LastnameField(help_text=' (Encryption: RSA local)', max_length=71, null=True),
        ),
    ]
