# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0004_auto_20160519_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupdiscussion',
            options={'get_latest_by': 'interview_datetime', 'verbose_name': 'Focus Group Discussion'},
        ),
        migrations.AlterModelOptions(
            name='historicalgroupdiscussion',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Focus Group Discussion'},
        ),
        migrations.AddField(
            model_name='historicalpotentialsubject',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='potentialsubject',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
