# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcpp_interview', '0005_auto_20160522_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpotentialsubject',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='potentialsubject',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
